apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: jenkins-pipeline
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - update
  - patch
  - delete
  - get
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - patch
  - delete
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  
