apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: slave
  name: slave
spec:
  containers:
  - name: node 
    image: node:lts-alpine
    command:
    - cat
    tty: true
  - name: kubectl
    image: alpine 
    command:
    - cat 
    tty: true
    volumeMounts:
    - name: kube
      mountPath: "/home/.kube"
      readOnly: true
    env:
    - name: KUBECONFIG  
      value: /home/.kube/config
  volumes:
  - name: kube
    secret:
      secretName: kube-config-66458m76b4