secretGenerator:
- name: kube-config
  namespace: jenkins
  files:
  - config
- name: docker-cred
  namespace: jenkins
  type: kubernetes.io/dockerconfigjson 
  files:
  - .dockerconfigjson
resources:
  - "ns.yml"
  - "sa-jenkins-pipeline.yml"
  - "clusterrole-jenkins-pipeline.yml"
  - "rolebindings.yml"
